services:
  postgresql:
    image: bitnami/postgresql:latest
    container_name: postgresql_event_sphere
    env_file:
      - .env
    environment:
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_PORT_NUMBER=${POSTGRESQL_PORT_NUMBER}
    ports:
      - "${POSTGRESQL_PORT_NUMBER}:${POSTGRESQL_PORT_NUMBER}"
    volumes:
      - postgresql_data_eventsphere:/bitnami/postgresql
    networks:
      - my_network


  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=a
      - PGADMIN_DEFAULT_PASSWORD=1234
    ports:
      - 3333:80
    depends_on:
      - postgresql
    networks:
      - my_network

volumes:
  postgresql_data_eventsphere:

networks:
  my_network:
    driver: bridge
